name: 'Skyhook Login to GCP GKE'
description: 'Authenticates to GCP, configures GKE kubeconfig, and logs into GAR'
author: 'Skyhook'

branding:
  icon: 'lock'
  color: 'purple'

inputs:
  credentials_json:
    description: 'GCP Service Account JSON credentials'
    required: false
  workload_identity_provider:
    description: 'Workload Identity Provider (for OIDC)'
    required: false
  service_account:
    description: 'Service Account email (for OIDC)'
    required: false
  project_id:
    description: 'GCP Project ID'
    required: true
  location:
    description: 'GKE cluster location (region or zone)'
    required: true
  cluster_name:
    description: 'GKE cluster name'
    required: false
  gar_location:
    description: 'Google Artifact Registry location (defaults to cluster location)'
    required: false
  skip_gar_login:
    description: 'Skip Google Artifact Registry login'
    required: false
    default: 'false'

outputs:
  project_id:
    description: 'GCP Project ID'
    value: ${{ inputs.project_id }}
  gar_registry:
    description: 'Google Artifact Registry URL'
    value: ${{ steps.gcp-config.outputs.gar_registry }}
  gar_logged_in:
    description: 'Whether GAR login was performed'
    value: ${{ steps.gar-status.outputs.logged_in }}
  kubectl_context:
    description: 'Kubectl context name'
    value: ${{ steps.gke-config.outputs.context }}

runs:
  using: 'composite'
  steps:
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ inputs.credentials_json }}
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}
        project_id: ${{ inputs.project_id }}
    
    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ inputs.project_id }}
    
    - name: Get GCP Configuration
      id: gcp-config
      shell: bash
      run: |
        # Determine GAR registry location
        if [ -n "${{ inputs.gar_location }}" ]; then
          GAR_LOCATION="${{ inputs.gar_location }}"
        else
          GAR_LOCATION="${{ inputs.location }}"
        fi
        
        # Always use location-specific endpoint (works for both multi-regional and regional)
        GAR_REGISTRY="${GAR_LOCATION}-docker.pkg.dev"
        
        FULL_REGISTRY="${GAR_REGISTRY}/${{ inputs.project_id }}"
        echo "gar_registry=$FULL_REGISTRY" >> $GITHUB_OUTPUT
        echo "GAR_REGISTRY=$FULL_REGISTRY" >> $GITHUB_ENV
        
        echo "ðŸ“‹ GCP Configuration:"
        echo "  Project ID: ${{ inputs.project_id }}"
        echo "  Location: ${{ inputs.location }}"
        echo "  GAR Registry: $FULL_REGISTRY"
    
    - name: Configure Docker for Artifact Registry
      id: gar-status
      if: inputs.skip_gar_login != 'true'
      shell: bash
      run: |
        echo "ðŸ” Configuring Docker for Google Artifact Registry..."

        # Get the registry hostname
        REGISTRY_HOST=$(echo "$GAR_REGISTRY" | cut -d'/' -f1)

        # Configure docker authentication
        gcloud auth configure-docker "$REGISTRY_HOST" --quiet

        echo "âœ… Docker configured for registry: $REGISTRY_HOST"
        echo "logged_in=true" >> $GITHUB_OUTPUT

    - name: Set GAR not logged in
      id: gar-status-false
      if: inputs.skip_gar_login == 'true'
      shell: bash
      run: |
        echo "logged_in=false" >> $GITHUB_OUTPUT
    
    - name: Get GKE credentials
      if: inputs.cluster_name != ''
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{ inputs.cluster_name }}
        location: ${{ inputs.location }}
        project_id: ${{ inputs.project_id }}

    - name: Configure kubectl for GKE
      if: inputs.cluster_name != ''
      id: gke-config
      shell: bash
      run: |
        echo "ðŸ”§ Configuring kubectl for GKE cluster: ${{ inputs.cluster_name }}"
        
        # Get the context name (GKE format)
        CONTEXT="gke_${{ inputs.project_id }}_${{ inputs.location }}_${{ inputs.cluster_name }}"
        echo "context=$CONTEXT" >> $GITHUB_OUTPUT
        
        # Set as current context
        kubectl config use-context "$CONTEXT"
        
        # Verify connection
        echo "âœ… Testing cluster connection..."
        kubectl cluster-info
        
        # Get cluster version
        CLUSTER_VERSION=$(kubectl version --short 2>/dev/null | grep "Server Version" || echo "Unknown")
        echo "  Cluster version: $CLUSTER_VERSION"
        
        # List namespaces to verify access
        echo "ðŸ“‹ Available namespaces:"
        kubectl get namespaces --no-headers 2>/dev/null | head -5 || true
        
        echo "âœ… Successfully configured kubectl for GKE cluster: ${{ inputs.cluster_name }}"